[project]
name = "testing-htmx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "jinja2>=3.1.6",
    "jinja2-fragments>=1.9.0",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
